config/routes.rb
require 'not_preferred_host'
Caijitie::Application.routes.draw do

  get "pv/index"

  # Rewrite non-preferred hosts in production
#  constraints(NotPreferredHost) do
#    get '/:path' => redirect { |params| "http://#{NotPreferredHost::PREFERRED_HOST}/#{params[:path]}" }
#  end

  # Root
  root :to => 'pages#home'

  # Blog
  get '/blog' => 'posts#index', :as => 'blog'


#  resources :posts, :only => [:show]
  resources :tags, :only => [:index, :show]

  get '/hot' => 'hot#index', :as => 'hot'
  get '/class' => 'class#index', :as => 'class'

  # Static pages
  get '/about' => 'pages#about', :as => 'about'
  get '/contact' => 'pages#contact', :as => 'contact'


  #search
  get "/search" => "search#index", :as => :search
  get "/category/:name" => "category#show", :constraints => {:name => /.*/}, :as => :category
  get "/author/:name" => "author#show" , :constraints => {:name => /.*/}, :as => :author

  #get "/download/tianya"
  get "/download/:id" => "download#show" , :constraints => {:name => /\d+/}, :as => :download


  #page-list 's page'
  resource :tb  do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :tysq do
    get 'page/:page', :action => :show
  end
  resource :dbht do
    get 'page/:page', :action => :show
  end
  resource :recent do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :active do
    get 'page/:page', :action => :show
  end
  resources :funs do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :posts do
    get 'page/:page', :action => :index, :on => :collection
  end


  #topic =》 post-page(page_url)
  resources :p do
    put :renew, :on => :member
    get :top, :on => :member

    resources :pu do
      get ':page', :action => :index, :on => :collection
    end
    get ':page', :action => :show, :on => :member
  end


  #easy_cai
    put "easy_cai/index"
    put "easy_cai/show"
    put "easy_cai/member"

  # Admin
  namespace :admin do
    root :to => 'posts#index'
    resources :posts, :only => [:show, :new, :create, :update, :edit, :destroy, :index]
    resources :tags, :only => [:new, :create, :update, :edit, :destroy, :index]
    resources :reports
    resources :easy_cais
    resources :topics
    get "topic_list/index"
    get "topic_list/tieba"
    get "topic_list/tianya"
    get "topic_list/douban"
  end

  get 'sitemap.xml' => 'sitemaps#sitemap'

 # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/pu_controller.rb
#encoding: utf-8
class PuController < ApplicationController
  caches_page :index
  #caches_action :index

  def index

    if params[:p_id]
      p_id = params[:p_id]
      page_id = params[:page]
      @topic = Topic.find(p_id)
      if @topic.blank? || @topic.status.eql?(9) || @topic.status.eql?(8)
        flash[:notice] = "对不起，打开出错，可能文章不存在或已经被删除！"
        redirect_to root_path
      end
      @page_urls = PageUrl.where("topic_id = ?  and (status = 0 or count > 0)", @topic.id).page(page_id)
      #获取当前页前后有文章的页
      #如果@page_urls为空 则返回
      return if @page_urls.blank?
      @page_url = @page_urls.first

      if (@page_url.status != 1 && @page_url.status != 2)
        @page_url.update_attributes!(:status => 2)
        puts "caiji online ********************"

        t = TiebaTuoshuiJob.get_tieba_post(@topic, @page_url) if @topic.rule == 1
        t = TianyabbsTuoshuiJob.get_tianyabbs_post(@topic, @page_url) if @topic.rule == 2
        t = DoubanhuatiTuoshuiJob.get_doubanhuati_post(@topic, @page_url) if @topic.rule == 3
        t = TianyabbsTechforumJob.get_tianyabbs_post(@topic, @page_url) if @topic.rule == 4
        t = TianyabbsBbsJob.get_tianyabbs_post(@topic, @page_url) if @topic.rule == 5

        @page_url.update_attributes!(:status => 1,:count => t ) if t >=  0 #读取正确 状态为 1
        @page_url.update_attributes!(:status => 9,:count => 0) if t == -1 #读取出错 状态 改为 9
      end

      @posts = @page_url.tieba_posts if @topic.section_id.eql?(1)
      @posts = @page_url.tianya_posts if @topic.section_id.eql?(2)
      @posts = @page_url.douban_posts if @topic.section_id.eql?(3)
      #@topic.increment!(:myshowtimes, by = 1)
      not_cai = PageUrl.count(:conditions => ["topic_id = ? and status = 0 ", @topic.id])
      if not_cai > 0  #存在为采集的页，本缓存失效
        all_page_num = PageUrl.count(:conditions => ["topic_id = ? ", @topic.id])
        1.upto(all_page_num) do |p|
         expire_page( :controller => "pu", :action => 'index' , :p_id => @topic.id, :page => p )
        end
      end
      #if @posts.blank?
        #expire_page( :controller => "pu", :action => 'index' , :p_id => @topic.id, :page => page_id )
        #redirect_to p_pu_path(@topic.id, 1) and return
      #end

      @temp_topics = Topic.where("section_id = ? and id < ?", @topic.section_id, @topic.id).order("id DESC").limit(10)

#获取当前页前后有文章的页
#@temp_pages = PageUrl.where("topic_id = ? and (status = 0 or count > 0)", @topic.id).limit(11)
#@temp_pages = PageUrl.where("topic_id = ? and (status = 0 or count > 0) and num > ?",  @topic.id, (page_id.to_i - 5)).limit(11)

    end

    #for seo
    #@fun = Fun.

  end
end

app/helpers/pu_helper.rb
module PuHelper
  def change_image_url str
    reg_img = Regexp.new("<img.[^>]*src(=| )(.[^>]*)>")

    mc = reg_img.match(str)
    str.gsub(reg_img, '<img')
    mc.each do |f|

    end
  end

  def show_page_list

  end
end

app/views/pu/_page_list.html.erb
<nav class="pagination round">
<% if @temp_pages and @temp_pages.length > 0 %>

    <% @temp_pages.each do |p| %>
          <% if p.num.to_s == params[:page] %>
          <span class="current"><%= "#{p.num}(#{p.count})" %></span>
          <% elsif p.status == 1 %>
              <%= link_to "#{p.num}(#{p.count})", "#{p.num}", :title => "#{p.count}帖" %>
          <% elsif p.status == 0 %>
              <%= link_to "#{p.num}(?)", "#{p.num}", :title => "立即脱水" %>
          <% end %>
    <% end %>
<% end %>
</nav>

app/views/pu/index.html.erb
<%- title "#{@topic.my_title} by #{@topic.author}.第#{params[:page]}页"  -%>

<%
  breadcrumb :tb_detail, @topic if @topic.section_id == 1
  breadcrumb :tysq_detail, @topic if @topic.section_id == 2
  breadcrumb :dbht_detail, @topic if @topic.section_id == 3
  meta  :description => "#{ @topic.my_title}_脱水版本,作者:#{ @topic.author},第#{params[:page]}页", :keywords => @topic.author
%>
<div class="container">
  <h1 class="round2 back"><%=	 @topic.my_title%></h1>
  <div class="row">
    <div class="col-xs-12">
      <script src="/js/bad_head.js"></script>
    </div>
  </div>
  <p>
  <span class="border">[<%= link_to '回目录', p_path(@topic), :target => '_blank', :class => 'red' %>]  </span>
  <span class="border">作者：<%= link_to @topic.author, author_path(@topic.author), :target => '_blank' %>  </span>
  <span class="border">文章类别：<%= link_to @topic.classname, category_path(@topic.classname),  :target => '_blank' %></span>
  <span class="border">共计<%=  @topic.mypostnum  %>回复/<%=  @topic.mypagenum  %>页</span>
  <span class="border">内容不完整？：<%= link_to '现在更新', renew_p_path(@topic.id), method: :put, :target => '_blank', rel: "nofollow", :class => 'red' %></span>
  <span class="border">查看原贴：<%= link_to '打开原贴', @topic.fromurl,  :target => '_blank' %></span>
  <span class="border"><%= link_to "赞" , top_p_path(@topic.id),  title: "#{@topic.top}", remote: true, "data-type" => :json, rel: "nofollow",  :id => "ajax_top"  %></span>
  <span class="border" id="num" style="display: none"></span>
  </p>
  <div class="row">
    <div class="col-xs-12">
      <%#=	 render 'page_list' %>
      <%= paginate @page_urls, :outer_window => 1, :inner_window => 1 -%>
      <% if !@posts.blank? %>
        <% @posts.each do |p| %>

          <div class="text-right small">
            <span><%= p.post_at.strftime("%Y-%m-%d %H:%M:%S") if p.post_at %></span>
            <span><%= p.my_level %>楼(<%= p.level %>)</span>
          </div>
          <div class="content round" style="word-break:break-all;overflow:hidden;">
            <%= raw p.content  %>
            <div style="text-align: center;">
              <% if p.my_level == 3 %>
                <script src="/js/bad_1lou.js"></script>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div style="color: red; margin-top:25px;" ><%= raw message %></div>
      <% end %>
      <%#=	 render 'page_list' %>
      <%= paginate @page_urls, :outer_window => 1, :inner_window => 1 -%>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <h4>相关阅读</h4>
      <script src="/js/bad_relation.js"></script>
      <% if @temp_topics && @temp_topics.length > 0 %>
        <ul>
          <% @temp_topics.each do |t| %>
            <li><%= link_to t.my_title, "/p/#{t.id}/pu/1", :target => '_blank', :class => "blue" %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>
<script src="/js/some_cad.js"></script>
<% if @topic.section_id == 1 %>
  <script src="/js/bd_1_img.js"></script>
<% elsif  @topic.section_id == 2 %>
  <script src="/js/ty_2_img.js"></script>
<% elsif  @topic.section_id == 3 %>
  <script src="/js/db_1_img.js"></script>

<%	end %>
<script src="/js/bad_xuanfu.js"></script>