config/routes.rb
require 'not_preferred_host'
Caijitie::Application.routes.draw do

  get "pv/index"

  # Rewrite non-preferred hosts in production
#  constraints(NotPreferredHost) do
#    get '/:path' => redirect { |params| "http://#{NotPreferredHost::PREFERRED_HOST}/#{params[:path]}" }
#  end

  # Root
  root :to => 'pages#home'

  # Blog
  get '/blog' => 'posts#index', :as => 'blog'


#  resources :posts, :only => [:show]
  resources :tags, :only => [:index, :show]

  get '/hot' => 'hot#index', :as => 'hot'
  get '/class' => 'class#index', :as => 'class'

  # Static pages
  get '/about' => 'pages#about', :as => 'about'
  get '/contact' => 'pages#contact', :as => 'contact'


  #search
  get "/search" => "search#index", :as => :search
  get "/category/:name" => "category#show", :constraints => {:name => /.*/}, :as => :category
  get "/author/:name" => "author#show" , :constraints => {:name => /.*/}, :as => :author

  #get "/download/tianya"
  get "/download/:id" => "download#show" , :constraints => {:name => /\d+/}, :as => :download


  #page-list 's page'
  resource :tb  do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :tysq do
    get 'page/:page', :action => :show
  end
  resource :dbht do
    get 'page/:page', :action => :show
  end
  resource :recent do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :active do
    get 'page/:page', :action => :show
  end
  resources :funs do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :posts do
    get 'page/:page', :action => :index, :on => :collection
  end


  #topic =》 post-page(page_url)
  resources :p do
    put :renew, :on => :member
    get :top, :on => :member

    resources :pu do
      get ':page', :action => :index, :on => :collection
    end
    get ':page', :action => :show, :on => :member
  end


  #easy_cai
    put "easy_cai/index"
    put "easy_cai/show"
    put "easy_cai/member"

  # Admin
  namespace :admin do
    root :to => 'posts#index'
    resources :posts, :only => [:show, :new, :create, :update, :edit, :destroy, :index]
    resources :tags, :only => [:new, :create, :update, :edit, :destroy, :index]
    resources :reports
    resources :easy_cais
    resources :topics
    get "topic_list/index"
    get "topic_list/tieba"
    get "topic_list/tianya"
    get "topic_list/douban"
  end

  get 'sitemap.xml' => 'sitemaps#sitemap'

 # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/topic.rb
#encoding: utf-8
class Topic < ActiveRecord::Base
  has_many :page_urls, :dependent => :delete_all
  has_many :tieba_posts, :through => :page_urls
  has_many :tianya_posts, :through => :page_urls
  has_many :douban_posts, :through => :page_urls

  has_one  :most_recent_page_url,
      :class_name => 'PageUrl',
      :order => 'num DESC'

  paginates_per 25

  def get_tieba_topic(url)
    t = TiebaTuoshuiJob.cai_tieba(url)
  end

  def get_tianya_topic(url)
    t, page_urls = TianyabbsTuoshuiJob.cai_tianyabbs_topic(url)
  end
  def get_tianya_techforum_topic(url)
    t, page_urls = TianyabbsTechforumJob.cai_tianyabbs_topic(url)
  end
  def get_tianya_bbs_topic(url)
    t, page_urls = TianyabbsBbsJob.cai_tianyabbs_topic(url)
  end
  
  

  def get_douban_topic(url, s)
    t = DoubanhuatiTuoshuiJob.cai_doubanhuati_topic(url, s)
  end
  
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < AdminController

  def index
    @topics = Topic.order("id DESC").page(params[:page]).per(50)
  end

  def show
    @topic = Topic.find(params[:id])
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [:admin, @topic], notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(topic_params)
        format.html { redirect_to [:admin, @topic], notice: 'Topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to admin_topics_url }
      format.json { head :ok }
    end
  end
  def topic_params  
    params.require(:topic).permit(:title ,:my_title,  :classname, :author, :top, :status, :tags)  
  end  


end

app/views/admin/topics/_form.html.erb
<%= form_for [:admin, @topic] do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title ,size: 100 %>
  </div>
  <div class="field">
    <%= f.label :my_title %><br />
    <%= f.text_field :my_title ,size: 100  %>
  </div>

  <div class="field">
    <%= f.label :classname %><br />
    <%= f.text_field :classname ,size: 100  %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author ,size: 100  %>
  </div>


  <div class="field">
    <%= f.label :top %><br />
    <%= f.text_field :top %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags ,size: 100  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @topic] %> |
<%= link_to 'Back', admin_topics_path %>

app/views/admin/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>标题</th>
    <th>原标题</th>
    <th>分类</th>
    <th>作者</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td class="blue"><%= topic.my_title %></td>
    <td><%= topic.title %></td>
    <td><%= topic.classname %></td>
    <td><%= topic.author %></td>
    <td><%= link_to 'Show', [:admin, topic] %></td>
    <td><%= link_to 'Edit', edit_admin_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', [:admin,topic], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
 <%= paginate @topics, :outer_window => 4, :inner_window => 4 -%>
<br />

<%= link_to 'New Topic', new_admin_topic_path %>

app/views/admin/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_topics_path %>

app/views/admin/topics/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>
<p>
  <b>MyTitle:</b>
  <%= @topic.my_title %>
</p>
<p>
  <b>Classname:</b>
  <%= @topic.classname %>
</p>

<p>
  <b>Author:</b>
  <%= @topic.author %>
</p>
<p>
  <b>top:</b>
  <%= @topic.top %>
</p>
<p>
  <b>status:</b>
  <%= @topic.status %>
</p>

<%= link_to 'Destroy', [:admin,@topic], confirm: 'Are you sure?', method: :delete %>
<%= link_to 'Edit', edit_admin_topic_path(@topic) %> |
<%= link_to 'Back', admin_topics_path %>