config/routes.rb
require 'not_preferred_host'
Caijitie::Application.routes.draw do

  get "pv/index"

  # Rewrite non-preferred hosts in production
#  constraints(NotPreferredHost) do
#    get '/:path' => redirect { |params| "http://#{NotPreferredHost::PREFERRED_HOST}/#{params[:path]}" }
#  end

  # Root
  root :to => 'pages#home'

  # Blog
  get '/blog' => 'posts#index', :as => 'blog'


#  resources :posts, :only => [:show]
  resources :tags, :only => [:index, :show]

  get '/hot' => 'hot#index', :as => 'hot'
  get '/class' => 'class#index', :as => 'class'

  # Static pages
  get '/about' => 'pages#about', :as => 'about'
  get '/contact' => 'pages#contact', :as => 'contact'


  #search
  get "/search" => "search#index", :as => :search
  get "/category/:name" => "category#show", :constraints => {:name => /.*/}, :as => :category
  get "/author/:name" => "author#show" , :constraints => {:name => /.*/}, :as => :author

  #get "/download/tianya"
  get "/download/:id" => "download#show" , :constraints => {:name => /\d+/}, :as => :download


  #page-list 's page'
  resource :tb  do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :tysq do
    get 'page/:page', :action => :show
  end
  resource :dbht do
    get 'page/:page', :action => :show
  end
  resource :recent do
    get 'page/:page', :action => :show#, :on => :collection
  end
  resource :active do
    get 'page/:page', :action => :show
  end
  resources :funs do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :posts do
    get 'page/:page', :action => :index, :on => :collection
  end


  #topic =》 post-page(page_url)
  resources :p do
    put :renew, :on => :member
    get :top, :on => :member

    resources :pu do
      get ':page', :action => :index, :on => :collection
    end
    get ':page', :action => :show, :on => :member
  end


  #easy_cai
    put "easy_cai/index"
    put "easy_cai/show"
    put "easy_cai/member"

  # Admin
  namespace :admin do
    root :to => 'posts#index'
    resources :posts, :only => [:show, :new, :create, :update, :edit, :destroy, :index]
    resources :tags, :only => [:new, :create, :update, :edit, :destroy, :index]
    resources :reports
    resources :easy_cais
    resources :topics
    get "topic_list/index"
    get "topic_list/tieba"
    get "topic_list/tianya"
    get "topic_list/douban"
  end

  get 'sitemap.xml' => 'sitemaps#sitemap'

 # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/admin/reports_controller.rb
#encoding: UTF-8
require 'nokogiri'
require 'open-uri'
class Admin::ReportsController < AdminController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    @topic_count = Topic.count
    @topic_count_9 = Topic.where(status: 9).count
    @page_status = PageUrl.find_by_sql("SELECT `status`, count(`status`) as count FROM `page_urls` GROUP BY `status` ")

    #@nottopic = PageUrl.find_by_sql("SELECT  count(id) as pagenum, topic_id FROM `page_urls`  WHERE `status` != 1  GROUP BY topic_id limit 50")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])
    @page_urls = PageUrl.where("status = 0").limit(@report.page_num)

    if(@page_urls.length.eql?(0))

      tianya_url('http://www.tianya.cn/publicforum/articleslist/0/funinfo.shtml')
      @bankuai.each do |t|
        if t[3].size >= 3 && t[3].size <= 4
          Delayed::Job.enqueue(PaJob.new(t[5]), -5)
        end
      end
    end

    @page_urls.each do |p|
      @topic = Topic.find(p.topic_id)
      Delayed::Job.enqueue(TuoingJob.new(@topic, p), -3)
    end

    respond_to do |format|
      if @report.save
        format.html { redirect_to [:admin,@report], notice: 'Report was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to [:admin,@report], notice: 'Report was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to admin_reports_url }
      format.json { head :ok }
    end
  end

  def tianya_url(url)
   html_stream  = open(url)
    regEx_tianya_1 = /tianya\.cn\/\w*\/\w*\/\w*\/[0-9]+\/[0-9]+\.shtml/
    doc = Nokogiri::HTML(html_stream)
   @bankuai_title = doc.css("title").text
    @bankuai = []
   if(doc.at_css("div#mainDiv > div#forumContentDiv > table"))
    doc.css("div#mainDiv > div#forumContentDiv > table").each do |item|
      if item.attr("name") == "adsp_list_post_info_a" || item.attr("name") == "adsp_list_post_info_b"
        @bankuai << [item.css("td")[1].text, item.css("td")[2].text, item.css("td")[3].text,
                    item.css("td")[4].text, item.css("td")[5].text, item.at_css("a").attr("href")]
      end
    end
   elsif (doc.css("div#postlistwrapper > table.listtable"))
      doc.css("div#postlistwrapper > table.listtable").each do |item|
         if item.attr("name") == "adsp_list_post_info_a" || item.attr("name") == "adsp_list_post_info_b"
            @bankuai <<  [item.css("td")[0].text, item.css("td")[1].text, item.css("td")[2].text, item.css("td")[3].text,
                        item.css("td")[4].text,  item.at_css("a").attr("href")]
         end

      end

   end
  rescue
    return ''
  end


end

app/views/admin/reports/_form.html.erb
<%= form_for([:admin,@report]) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :topic_num %><br />
    <%= f.number_field :topic_num %>
  </div>
  <div class="field">
    <%= f.label :page_num ,'本次采集数量' %><br />
    <%= f.number_field :page_num %>
  </div>
  <div class="field">
    <%= f.label :pagenot_num %><br />
    <%= f.number_field :pagenot_num %>
  </div>
  <div class="field">
    <%= f.label :tieba_num %><br />
    <%= f.number_field :tieba_num %>
  </div>
  <div class="field">
    <%= f.label :douban_num %><br />
    <%= f.number_field :douban_num %>
  </div>
  <div class="field">
    <%= f.label :tianyabbs_num %><br />
    <%= f.number_field :tianyabbs_num %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', admin_reports_path %>

app/views/admin/reports/index.html.erb
<h2>
    采集页情况
</h2>
<p>
主题数量:<%= @topic_count %><br/>
关闭主题:<%= @topic_count_9 %>
</p>

<p>
<table>
  <tbody>
    <tr>
      <th>Page状态|</th>
      <th>数量</th>
    </tr>
  <% if @page_status && @page_status.length > 0 %>
    <%	 @page_status.each do |p| %>
      <tr>
        <td><%= p.status %></td>
        <td><%= p.count %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
</p>
<h2>
  采集任务
</h2>
<%= link_to '新建采集任务', new_admin_report_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Topic num</th>
    <th>Page num</th>
    <th>Pagenot num</th>
    <th>Tieba num</th>
    <th>Douban num</th>
    <th>Tianyabbs num</th>
    <th>note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.name %></td>
    <td><%= report.topic_num %></td>
    <td><%= report.page_num %></td>
    <td><%= report.pagenot_num %></td>
    <td><%= report.tieba_num %></td>
    <td><%= report.douban_num %></td>
    <td><%= report.tianyabbs_num %></td>
    <td><%= report.note %></td>
    <td><%= link_to 'Show', [:admin, report] %></td>
    <td><%= link_to 'Edit', edit_admin_report_path(report) %></td>
    <td><%= link_to 'Destroy', [:admin,  report], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Report', new_admin_report_path %>

<br />
<p>
  <table>
    <tbody>
          <tr>
      <th>序号</th>
      <th>编号</th>
      <th>未采集页</th>
    </tr>

      </tbody>
</table>
</p>

app/views/admin/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_reports_path %>

app/views/admin/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @report.name %>
</p>

<p>
  <b>Topic num:</b>
  <%= @report.topic_num %>
</p>

<p>
  <b>本次采集数量:</b>
  <%= @report.page_num %>
</p>

<p>
  <b>Pagenot num:</b>
  <%= @report.pagenot_num %>
</p>

<p>
  <b>Tieba num:</b>
  <%= @report.tieba_num %>
</p>

<p>
  <b>Douban num:</b>
  <%= @report.douban_num %>
</p>

<p>
  <b>Tianyabbs num:</b>
  <%= @report.tianyabbs_num %>
</p>


<%= link_to 'Edit', edit_admin_report_path(@report) %> |
<%= link_to 'Back', admin_reports_path %>